### ISSUE TITLE
Fresh install of swift-account-caretaker results in ImportError: No module named swift.account.backend

### ISSUE THREAD

**Issue by timolow** [sapcc/swift-account-caretaker#14]
Howdy,

Love the idea of this script and would like to audit our swift fleet with script however after install both manual and via pip results in import error as seen below:

(swift-r14.14.0) root@infra1-swift-proxy-container-4e5b2a66:~/swift-account-caretaker# swift-account-caretaker
Traceback (most recent call last):
  File "/usr/local/bin/swift-account-caretaker", line 18, in <module>
    import caretaker.accounts as acc
  File "/usr/local/lib/python2.7/dist-packages/caretaker/accounts.py", line 25, in <module>
    from swift.account.backend import AccountBroker, DATADIR
ImportError: No module named swift.account.backend

Please advise anything that could be causing this.

Thanks,

Tim

**Comment by reimannf** [comment]
Hi Tim. Well the requirements are not maintained very well. You need to run this with the `swift-account` server code. So either run it on the account server or you need to install the complete swift package.

**Comment by timolow** [comment]
Perfect! Thanks for that, seems to be workingish, having some issues with redirection from internalURL to publicURL but making progress!

Tim
